remote_theme: just-the-docs/just-the-docs
title: Justin Portfolio
description: Technical Writing Samples

# Force the navigation to render
nav_config:
  show_full_navigation: true

# External Link (Ensure 2 spaces before the name)
aux_links:
  "My GitHub": "https://github.com/justingilmore-docs"

# Feature Toggles
search_enabled: true
heading_anchors: true
